#!/bin/bash
hwDir=/sys/class/drm/card
monitorDir=/sys/kernel/debug/dri/

function invalidPercent {
    echo "Invalid percentage. Skipping."
}

echo "This script will allow you to set custom fan and clock (core and memory) speeds for AMD cards."
echo
echo
echo "The following cards are available: "
ls -d1 $hwDir?|cut -f5 -d'/'
echo
read -p "Enter the card number you would like to modify: " cardNum
echo

while [ ! -d $hwDir$cardNum -a ! -d $monitorDir$cardNum ]
do
    echo "$cardNum is not a valid number"
    echo "The following cards are available: "
    ls -d1 $hwDir?|cut -f5 -d'/'
    echo
    read -p "Enter the card number you would like to modify: " cardNum
    echo
done

read -p "Enter the manual fan speed percentage 1-100 (or 0 for auto fan speed): " fanSpeed

if [ $fanSpeed -eq 0 ]
then
    echo "Fan speed has not been manually set"
elif [ $fanSpeed -ge 1 -a $fanSpeed -le 100 ]
then
    sudo echo "1" > $hwDir$cardNum/device/hwmon/hwmon0/pwm1_enable
    sudo echo $fanSpeed > $hwDir$cardNum/device/hwmon/hwmon0/pwm1
    echo "Fan speed set to $fanSpeed%"
else
    invalidPercent
fi
echo

echo "Enter the Core Clock overclock percentage 1-100 (0 for none)"
read -p "negative percentages will underclock the card: " coreClk

if [ $coreClk -eq 0 ]
then
    echo "Core clock has not been changed"
elif [ $coreClk -ge -100 -a $coreClk -le 100 ]
then
    sudo echo $coreClk > $hwDir$cardNum/device/pp_sclk_od
    echo "Core clock changed by $coreClk%"
else
    invalidPercent
fi
echo

echo "Enter the Memory Clock overclock percentage 1-100 (0 for none)"
read -p "negative percentages will underclock the card: " memClk

if [ $memClk -eq 0 ]
then
    echo "Memory clock has not been changed"
elif [ $memClk -ge -100 -a $memClk -le 100 ]
then
    sudo echo $memClk > $hwDir$cardNum/device/pp_mclk_od
    echo "Core clock changed by $memClk%"
else
    invalidPercent
fi

echo
echo
echo "Complete! The card monitor will now start..."
read -p "Press Enter to continue or Ctrl + c to exit"
sudo watch cat $monitorDir$cardNum/amdgpu_pm_info