#!/bin/bash
hwDir=/sys/class/drm/card
monitorDir=/sys/kernel/debug/dri/

function setFan {
    if [ $1 -a $2 ]
    then
        echo "Setting fan speed to $2%"

        hwmonDir=$(ls $hwDir$1/device/hwmon/)

        if [ -z $hwmonDir ]
        then
            echo "Unable to detect fan controls. Fan speed not set"
            echo "Did you run the detect-temp-sensors script?"
            echo
        else
            sudo echo "1" > $hwDir$1/device/hwmon/$hwmonDir/fan1_enable
            sudo echo $( echo "$( cat $hwDir$1/device/hwmon/$hwmonDir/fan1_max | tr -d '\n' ) * $( echo "scale=2; $2/100" | bc )" | bc | cut -d'.' -f 1) > $hwDir$1/device/hwmon/$hwmonDir/fan1_target
        fi
    else
        echo "Missing setFan parameters"
    fi
}

function setClock {
    if [ $1 -a -n $2 -a $3 ]
    then
        clkType=pp_sclk_od
        
        if [ $3 == "memory" ]
        then
            clkType=pp_mclk_od
        fi

        echo "Changing $3 clock by $2%"
        sudo echo $2 > $hwDir$1/device/$clkType
    else
        echo "Missing setClock parameters"
    fi
}

function invalidPercent {
    echo "Invalid percentage. Skipping."
}

# Pass the following parameters to automate this script
# $1 = cardNum  //The card number you would like to use
# $2 = fanSpeed //Desired manual fan speed percentage
# $3 = coreClk  //Desired core clock percentage 
# $4 = memClk   //Desired memory clock percentage
# $5 = Show Monitor (0 false, 1 true)
if [ $1 ] && [ $2 ] && [ $3 ] && [ $4 ] && [ $5 ]
then
    if [ ! -d $hwDir$1 -a ! -d $monitorDir$1 ]
    then
        echo "Invalid card number"
    else
        echo "Configuring card$1"
        setFan $1 $2
        setClock $1 $3 "core"
        setClock $1 $4 "memory"

        if [ $5 -eq 1 ]
        then
            sudo watch cat $monitorDir$1/amdgpu_pm_info
        fi
    fi
exit
fi


echo "This script will allow you to set custom fan and clock (core and memory) speeds for AMD cards."
echo
echo
echo "The following cards are available: "
ls -d1 $hwDir?|cut -f5 -d'/'
echo
read -p "Enter the card number you would like to modify: " cardNum
echo

while [ ! -d $hwDir$cardNum -a ! -d $monitorDir$cardNum ]
do
    echo "$cardNum is not a valid number"
    echo "The following cards are available: "
    ls -d1 $hwDir?|cut -f5 -d'/'
    echo
    read -p "Enter the card number you would like to modify: " cardNum
    echo
done

read -p "Enter the manual fan speed percentage 1-100 (or 0 for auto fan speed): " fanSpeed

if [ $fanSpeed -eq 0 ]
then
    echo "Fan speed has not been manually set"
elif [ $fanSpeed -ge 1 -a $fanSpeed -le 100 ]
then
    setFan $cardNum $fanSpeed
else
    invalidPercent
fi
echo

echo "Enter the Core Clock overclock percentage 1-100 (0 for none)"
read -p "negative percentages will underclock the card: " coreClk

if [ $coreClk -eq 0 ]
then
    echo "Core clock has not been changed"
elif [ $coreClk -ge -100 -a $coreClk -le 100 ]
then
    setClock $cardNum $coreClk "core"
else
    invalidPercent
fi
echo

echo "Enter the Memory Clock overclock percentage 1-100 (0 for none)"
read -p "negative percentages will underclock the card: " memClk

if [ $memClk -eq 0 ]
then
    echo "Memory clock has not been changed"
elif [ $memClk -ge -100 -a $memClk -le 100 ]
then
    setClock $cardNum $memClk "memory"
else
    invalidPercent
fi

echo
echo
echo "Complete! The card monitor will now start..."
read -p "Press Enter to continue or Ctrl + c to exit"
sudo watch cat $monitorDir$cardNum/amdgpu_pm_info
