#!/bin/bash
set -a
source ~/mining/config.txt
set +a
minerPath=$(cat ~/mining/.ethminerpath)

printf "\n\n\n************$(date)************\n\n\n" >> ~/mining/logs/mining.log
~/mining/ethminer/$minerPath/bin/ethminer -HWMON 1 $params --farm-recheck 200 \
-P $protocol://$wallet.$rig@$stratum1 -P $protocol://$wallet.$rig@$stratum2 \
-RH 2>&1 | tee -a ~/mining/logs/mining.log