#!/bin/bash
version=amdgpu-pro-17.40-483984
baseURL=https://www2.ati.com/drivers/linux/beta/ubuntu/
referURL=http://support.amd.com

cd ~/mining/downloads/
wget --referer=$referURL $baseURL$version.tar.xz
tar -Jxvf $version.tar.xz
cd $version
./amdgpu-pro-install -y
sudo usermod -a -G video $LOGNAME
sudo apt install -y rocm-amdgpu-pro
echo 'export LLVM_BIN=/opt/amdgpu-pro/bin' | sudo tee /etc/profile.d/amdgpu-pro.sh
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&amdgpu.vm_fragment_size=9 /'  /etc/default/grub
sudo update-grub
echo "Please reboot the system for the changes to take effect"
