#!/bin/bash
cd ~/mining/downloads/
wget --referer=http://support.amd.com https://www2.ati.com/drivers/linux/beta/ubuntu/amdgpu-pro-17.40-483984.tar.xz
tar -Jxvf amdgpu-pro-17.40-483984.tar.xz
cd amdgpu-pro-17.40-483984
./amdgpu-pro-install -y
sudo usermod -a -G video $LOGNAME
sudo apt install -y rocm-amdgpu-pro
echo 'export LLVM_BIN=/opt/amdgpu-pro/bin' | sudo tee /etc/profile.d/amdgpu-pro.sh
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&amdgpu.vm_fragment_size=9 /'  /etc/default/grub
sudo update-grub
echo "Please reboot the system for the changes to take effect"
