#!/bin/bash
echo
echo " ************ Installing required software ************ "
sudo apt update
sudo apt upgrade -y

if [ ! $(which htop) ]
then
    sudo apt install -y htop
fi

if [ ! $(which sensors) ]
then
    sudo apt install -y lm-sensors
fi

sleep 1
echo
echo " ************ Setting up scheduled task ************ "
cd ~/mining/
crontab .customCron

sleep 1
echo
echo " ************ Setting permissions ************ "
chmod +x -vR ~/mining/scripts/* ~/mining/setup/*

sleep 1
echo
echo " ************ Creating shortcuts ************ "
ln -v -s ~/mining/scripts/start ~/
ln -v -s ~/mining/scripts/update ~/
ln -v -s ~/mining/scripts/getNewMiner ~/
